### ISSUE TITLE
Nightly test 

### ISSUE THREAD

**Issue by Akilan1999** [vitessio/arewefastyet#1]
Task:
1. To create a vps using packet 
    - Deploy Spot Market Servers 
       - Location : NY5 - Secaucus, NJ
        - n2large.xlarge.x86
        - OS : Ubuntu 20.04 or CentOS 8 

2. Run @dkhenry Ansible or Build Vitess and run Sysbench on Vitess Mysql 
3. Create a scheduler that runs every night and stores the result in a database

**Comment by dkhenry** [comment]
1. Doesn't need to be spot market 
2. You should be able to build any version of Vitess ( both the main branch, and tags, and any in progress branch ) 
3. When you store the data make sure you store
[ ] The Date and Time the test was run 
[ ] the test job that was run ( TPCC or OLAP ) 
[ ] the commit the test was ran against 
[ ] The Transactions per second
[ ] The queries per second 
[ ] The Average Latency 
[ ] The Max latency 
[ ] the P95,P99 Latency 
[ ] The total time the test took.
