### ISSUE TITLE
Implementing Request benchmark run 

### ISSUE THREAD

**Issue by Akilan1999** [vitessio/arewefastyet#140]
## Intro
Request benchmark ensures that a user can request to run the benchmark based on commit hash from the Vitess main branch or a specific Vitess version. 

## After request 
- Send message to slack group 
- Insert request into the databases  

## Fields
- Commit hash or Vitess version 
- Name 
- Email

**Comment by frouioui** [comment]
The API route for this has been completed in https://github.com/vitessio/arewefastyet/pull/464. @marsian83 is currently working on the UI. Closing this issue for now.
