### ISSUE TITLE
benchmark site has no useful information in it.

### ISSUE THREAD

**Issue by CKarper** [vitessio/arewefastyet#263]
**Describe the bug**
The benchmark website has no results/is broken.

**To Reproduce**
1. Go to 'https://benchmark.vitess.io'
2. Click on 'Macro', 'Micro', or 'vs'
3. See error

2b. `CRON` is also broken, in a different way.

**Expected behavior**
Something useful to judge performance to be displayed.

None of the rest is significant.

**Screenshots**

![image](https://user-images.githubusercontent.com/653156/128803577-54aefd0a-83e1-4883-bb62-94f6871cf768.png)

![image](https://user-images.githubusercontent.com/653156/128803696-eb0ba46a-c5c8-4087-a407-a30181b6e895.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by frouioui** [comment]
Hello @CKarper, thank you very for detailing this issue. I've investigated the issue and found that it is link to TLS certificates not being up to date when used against our internal database. While I work on a long term patch for this issue, I have manually restarted the web server and the website renders useful information again.
