### ISSUE TITLE
https://benchmark.vitess.io/ website not working !

### ISSUE THREAD

**Issue by mdnfiras** [vitessio/arewefastyet#330]
**Describe the bug**
https://benchmark.vitess.io/ is not working.

**To Reproduce**
1. Go to https://benchmark.vitess.io/

**Expected behavior**
The website should show up.

**Screenshots**
<img width="726" alt="image" src="https://user-images.githubusercontent.com/29513074/208433761-b7ba2109-0ff2-4961-aae7-853dbe6d4be1.png">

**Comment by frouioui** [comment]
This has been fixed! Thank you
