### ISSUE TITLE
Redesign the dropdowns on the macro and micro page

### ISSUE THREAD

**Issue by Camillemtd** [vitessio/arewefastyet#389]
Currently, both dropdowns are below the title, but I would like to insert the dropdowns directly into the title to make a change. Therefore, I need to rethink the design of both dropdowns to ensure they are consistent with the title.

**Comment by punithnayak** [comment]
Hey @Camillemtd  @frouioui can i work on this issue?

**Comment by punithnayak** [comment]
![image](https://github.com/vitessio/arewefastyet/assets/110713318/51a9657b-6580-4ae6-9f9b-059a2dac0e6f)
Hey I have come up with simple design we can discuss furthur

**Comment by Camillemtd** [comment]
Hi @punithnayak , sorry for responding so late. I hadn't seen your message, but I've finished working on it for now. Thanks for your help!
<img width="909" alt="Capture d’écran 2023-08-02 à 16 09 03" src="https://github.com/vitessio/arewefastyet/assets/116645689/bf7ff861-4369-439d-9769-365aef1ea146">
<img width="943" alt="Capture d’écran 2023-08-02 à 16 08 56" src="https://github.com/vitessio/arewefastyet/assets/116645689/25023574-19a0-48db-97fc-1df058b8b3e1">
