### ISSUE TITLE
Fix: eslint warnings and errors

### ISSUE THREAD

**Issue by punithnayak** [vitessio/arewefastyet#414]
There are bunch of eslint waning in the website dir
` /home/punith/Desktop/lfx/arewefastyet/website/src/App.jsx
  18:8  error  'React' is defined but never used  no-unused-vars

ueue.jsx
  17:8    error  'React' is defined but never used                                                                                                                                                      no-unused-vars
  21:20   error  'data' is missing in props validation                                                                                                                                                  react/prop-types
  24:35   error  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
  24:110  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  24:127  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  24:135  error  'data.git_ref.slice' is missing in props validation                                                                                                                                    react/prop-types
  25:49   error  'data.source' is missing in props validation                                                                                                                                           react/prop-types
  26:49   error  'data.type_of' is missing in props validation                                                                                                                                          react/prop-types
  27:48   error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types

/home/punith/Desktop/lfx/arewefastyet/website/src/components/StatusComponents/PreviousExeResponsiveMobile/PreviousExeResMobile.jsx
  17:8    error  'React' is defined but never used                                                                                                                                                      no-unused-vars
  23:26   error  'data' is missing in props validation                                                                                                                                                  react/prop-types
  23:32   error  'className' is missing in props validation                                                                                                                                             react/prop-types
  38:53   error  'data.source' is missing in props validation                                                                                                                                           react/prop-types
  39:63   error  'data.status' is missing in props validation                                                                                                                                           react/prop-types
  39:102  error  'data.status' is missing in props validation                                                                                                                                           react/prop-types
  57:46   error  'data.uuid' is missing in props validation                                                                                                                                             react/prop-types
  57:51   error  'data.uuid.slice' is missing in props validation                                                                                                                                       react/prop-types
  58:40   error  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
  58:115  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  58:132  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  58:140  error  'data.git_ref.slice' is missing in props validation                                                                                                                                    react/prop-types
  59:46   error  'data.type_of' is missing in props validation                                                                                                                                          react/prop-types
  60:56   error  'data.started_at' is missing in props validation                                                                                                                                       react/prop-types
  61:56   error  'data.finished_at' is missing in props validation                                                                                                                                      react/prop-types
  62:46   error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types
  63:45   error  'data.golang_version' is missing in props validation                                                                                                                                   react/prop-types

/home/punith/Desktop/lfx/arewefastyet/website/src/components/StatusComponents/PreviousExecutionResponsiveTablet/PreviousExeResTablet.jsx
  17:8   error  'React' is defined but never used                                                                                                                                                      no-unused-vars
  27:33  error  'data' is missing in props validation                                                                                                                                                  react/prop-types
  27:39  error  'className' is missing in props validation                                                                                                                                             react/prop-types
  45:11  error  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
  47:69  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  49:19  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  49:27  error  'data.git_ref.slice' is missing in props validation                                                                                                                                    react/prop-types
  52:45  error  'data.source' is missing in props validation                                                                                                                                           react/prop-types
  53:56  error  'data.started_at' is missing in props validation                                                                                                                                       react/prop-types
  54:56  error  'data.finished_at' is missing in props validation                                                                                                                                      react/prop-types
  57:18  error  'data.status' is missing in props validation                                                                                                                                           react/prop-types
  60:17  error  'data.status' is missing in props validation                                                                                                                                           react/prop-types
  78:31  error  'data.uuid' is missing in props validation                                                                                                                                             react/prop-types
  78:36  error  'data.uuid.slice' is missing in props validation                                                                                                                                       react/prop-types
  79:31  error  'data.type_of' is missing in props validation                                                                                                                                          react/prop-types
  80:31  error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types
  81:31  error  'data.golang_version' is missing in props validation                                                                                                                                   react/prop-types

/home/punith/Desktop/lfx/arewefastyet/website/src/components/StatusComponents/PreviousExecutions/PreviousExe.jsx
  17:8   error  'React' is defined but never used                                                                                                                                                      no-unused-vars
  22:24  error  'data' is missing in props validation                                                                                                                                                  react/prop-types
  25:43  error  'data.uuid' is missing in props validation                                                                                                                                             react/prop-types
  25:48  error  'data.uuid.slice' is missing in props validation                                                                                                                                       react/prop-types
  27:9   error  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
  29:67  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  31:17  error  'data.git_ref' is missing in props validation                                                                                                                                          react/prop-types
  31:25  error  'data.git_ref.slice' is missing in props validation                                                                                                                                    react/prop-types
  34:52  error  'data.source' is missing in props validation                                                                                                                                           react/prop-types
  36:26  error  'data.started_at' is missing in props validation                                                                                                                                       react/prop-types
  39:26  error  'data.finished_at' is missing in props validation                                                                                                                                      react/prop-types
  41:43  error  'data.type_of' is missing in props validation                                                                                                                                          react/prop-types
  43:15  error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types
  46:11  error  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
  48:67  error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types
  50:19  error  'data.pull_nb' is missing in props validation                                                                                                                                          react/prop-types
  54:42  error  'data.golang_version' is missing in props validation                                                                                                                                   react/prop-types
  56:48  error  'data.status' is missing in props validation                                                                                                                                           react/prop-types
  58:15  error  'data.status' is missing in props validation                                                                                                                                           react/prop-types

/home/punith/Desktop/lfx/arewefastyet/website/src/components/footer/Footer.jsx
  17:8  error  'React' is defined but never used  no-unused-vars

/home/punith/Desktop/lfx/arewefastyet/website/src/components/header/Header.jsx
  17:8  error  'React' is defined but never used  no-unused-vars

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/CRON/CRON.jsx
   17:8   error    'React' is defined but never used                                                                                             no-unused-vars
   20:10  error    'ResponsiveLine' is defined but never used                                                                                    no-unused-vars
   87:6   warning  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array                   react-hooks/exhaustive-deps
  317:16  warning  Fast refresh only works when a file only export components. Use a new file to share constant or functions between components  react-refresh/only-export-components

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/Compare/Compare.jsx
  17:8   error    'React' is defined but never used                                                                            no-unused-vars
  63:16  error    'isMicrobenchLoading' is assigned a value but never used                                                     no-unused-vars
  64:12  error    'microbenchError' is assigned a value but never used                                                         no-unused-vars
  80:6   warning  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/Home/Home.jsx
  17:8  error  'React' is defined but never used  no-unused-vars

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/Layout.jsx
  17:8   error  'React' is defined but never used     no-unused-vars
  17:17  error  'useState' is defined but never used  no-unused-vars

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/Macro/Macro.jsx
   74:10  warning  React Hook useEffect has missing dependencies: 'gitRefLeft' and 'gitRefRight'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
   96:8   warning  React Hook useEffect has a missing dependency: 'isFirstCallFinished'. Either include it or remove the dependency array             react-hooks/exhaustive-deps
  105:8   warning  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array                        react-hooks/exhaustive-deps

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/MacroQueriesCompare/MacroQueriesCompare.jsx
  17:8   error    'React' is defined but never used                                                                                                                       no-unused-vars
  29:22  error    'setcommitLeft' is assigned a value but never used                                                                                                      no-unused-vars
  32:23  error    'setcommitRight' is assigned a value but never used                                                                                                     no-unused-vars
  35:16  error    'settype' is assigned a value but never used                                                                                                            no-unused-vars
  42:6   warning  React Hook useEffect has missing dependencies: 'commitLeft', 'commitRight', 'navigate', and 'type'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  70:6   warning  React Hook useEffect has missing dependencies: 'commitLeft', 'commitRight', and 'type'. Either include them or remove the dependency array              react-hooks/exhaustive-deps

/home/punith/Desktop/lfx/arewefastyet/website/src/pages/Micro/Micro.jsx
   75:6  warning  React Hook useEffect has missing dependencies: 'gitRefLeft' and 'gitRefRight'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

  74:3  error  'setChangeUrl' is defined but never used  no-unused-vars

✖ 854 problems (841 errors, 13 warnings)
  5 errors and 0 warnings potentially fixable with the `--fix` option.`

**Comment by punithnayak** [comment]
Hey @frouioui I wanna participate in upcomming lfx program so I wanna take this as beginners issue is it ok?

**Comment by punithnayak** [comment]
I also have plans to run 'npm run lint' in CI preventing further eslint error

**Comment by frouioui** [comment]
You are very welcome to open a Pull Request @punithnayak and @Camillemtd and I will then review it.

**Comment by sivasathyaseeelan** [comment]
Hello @frouioui, can I work on this issue?

**Comment by frouioui** [comment]
Hey @sivasathyaseeelan! It does not seem like @punithnayak has not picked this up yet, you're welcome to go ahead.

**Comment by punithnayak** [comment]
Hey@frouioui  will come up with pr by Tomorrow got stuck...a bit

**Comment by Lucif3r-in** [comment]
I think #420 solves many of these errors and the warnings can be removed by removing unused codes some of which are still WIP.

**Comment by frouioui** [comment]
Closing this for now.
