### ISSUE TITLE
feat: Use meta tags to control how your website appears in search results

### ISSUE THREAD

**Issue by Lucif3r-in** [vitessio/arewefastyet#418]
**Is your feature request related to a problem? Please describe.**
Feature

**Describe the solution you'd like**
I want to add og meta tags similar to vitess website to improve how website looks when shared

**Additional context**

P.S - I want to work on it.

**Comment by frouioui** [comment]
Hello @Lucif3r-in thank you for opening this issue. This sounds interesting, feel free to open a Pull Request with the proposed fix and @Camillemtd and I will review it.
