### ISSUE TITLE
[FEATURE]: Use styled-components for CSS-in-JS instead of plain CSS 

### ISSUE THREAD

**Issue by Lucif3r-in** [vitessio/arewefastyet#426]
**Is your feature request related to a problem? Please describe.**
I've identified some challenges in our project's current styling approach using plain CSS, and I believe these challenges are impeding our development efficiency and codebase maintainability. The issues we're facing include:
- **Global Scope Conflicts:** Plain CSS leads to class name clashes and unintended style overrides across components.

- **Lack of Encapsulation:** Global CSS makes it hard to contain styles within components, resulting in unwanted styling bleeding into others.

- **Complexity and Maintenance:** Managing multiple CSS files and dependencies is becoming overwhelming.

- **Performance Impact:** Large CSS files affect our site's loading speed, especially on slower networks.

**Describe the solution you'd like**
I propose adopting `styled-components` for styling in our project to address these challenges:

- **Scoped Styles**: `styled-components` keeps styles scoped to components, eliminating global scope issues.

- **Component-based Styling**: It enables the creation of reusable styled components, improving code organization and maintainability.

- **Dynamic Styling**: `styled-components` allows styles to change dynamically based on component props, enhancing flexibility.

- **Performance Benefits**: The library generates optimized styles for each component, resulting in improved performance.

  - **Enhanced Performance**: `styled-components` can improve website performance by generating optimized styles for each component. This means that only the necessary styles are included in the final CSS, leading to reduced file sizes and faster loading times. As a result, our website's user experience will be enhanced, particularly on slower network connections and devices.
  

**Describe alternatives you've considered**
I've reviewed options:

- **CSS Modules**: Limited encapsulation compared to `styled-components`.
But CSS-in-JS stands ahead always, so we should consider implementing it.

P.S - I would like to work on it.

**Comment by ChaudharyRaman** [comment]
Hi @Lucif3r-in. Please assign me this issue.

**Comment by Lucif3r-in** [comment]
Hey @ChaudharyRaman, thank you for your interest but I will be working on this issue if approved by the mentors as I have already mentioned.

**Comment by Lucif3r-in** [comment]
@frouioui If you agree with this suggestion I can work on it.

**Comment by frouioui** [comment]
Hello! Thank you for opening this, @marsian83 has been working on removing some of our CSS and using Tailwind instead. @marsian83 do you reckon we can close this issue?

**Comment by marsian83** [comment]
Yes, since we use tailwind now, this won't be needed as we longer face most of the highlighted issues
