### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by frouioui** [vitessio/arewefastyet#43]
Add and create new contribution guidelines for this project.

**Comment by Akilan1999** [comment]
Is there any documentation for building the project using Go and in the master branch is python fully deprecated. The makefile is linked to the python library ```bench_cli```.

**Comment by frouioui** [comment]
> Is there any documentation for building the project using Go and in the master branch is python fully deprecated. The makefile is linked to the python library `bench_cli`.

@Akilan1999 - Pull request #195 adds a few rules to build and test the golang code using the Makefile.

**Comment by frouioui** [comment]
This is not needed for now.
