### ISSUE TITLE
Arewemobileyet: make this site mobile responsive

### ISSUE THREAD

**Issue by Maniktherana** [vitessio/arewefastyet#500]
**Is your feature request related to a problem? Please describe.**
Currently, this site isn't mobile responsive. Accommodating mobile screens is a must on all websites. Critical information may be hidden when viewing from smaller viewports. 

![image](https://github.com/vitessio/arewefastyet/assets/14011425/de9142c8-0761-44e9-9a7c-de7d499059c4)![image](https://github.com/vitessio/arewefastyet/assets/14011425/beae0547-16d5-4391-9717-d539822b8103)
**Describe the solution you'd like**
This will involve adding media queries and possibly separate, mobile-only components such as a mobile navbar.

**Comment by marsian83** [comment]
Hi @Maniktherana, you may check the responsiveness in #469 
The PR has not yet been merged as some minor changes are to be made still 
But you may check if there are any missing portions of responsive behavior in that PR's head

**Comment by Maniktherana** [comment]
@marsian83 Ah didnt realize, I'll check it out

**Comment by frouioui** [comment]
this has been fixed/implemented by @Jad31
