### ISSUE TITLE
Feat: Replacing twitter icon with the new one

### ISSUE THREAD

**Issue by DhairyaMajmudar** [vitessio/arewefastyet#530]
**Is your feature request related to a problem? Please describe.**

Replacing the Twitter ( Blue Bird ) logo with the new X logo.

**Describe the solution you'd like**
In the file `website/src/common/Fotter.tsx` AiFillTwitterCircle is imported from react icons replacing this from FaSquareXTwitter can perform the desired task. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by frouioui** [comment]
That's a good point. Thank you for raising this.
