### ISSUE TITLE
Feat: Adding new issue and PR templates

### ISSUE THREAD

**Issue by DhairyaMajmudar** [vitessio/arewefastyet#532]
**Is your feature request related to a problem? Please describe.**
currently, we are using `.md` files for issue template and PR template which can be replaced by `.yml` templates. 

**Benefits**
This will help issue and PR creators to quickly summit them by just filling the data in the placeholder fields. Saving their time and making issue and PR board consistent. 

Automatically labels the  issue differentiating them on the basics of  bug or feature

**Describe the solution you'd like**
Creating new issue and pr `.yml` templates.

**Describe alternatives you've considered**
N/A

**Additional context**

After creating the new templates they will look like this 

![image](https://github.com/vitessio/arewefastyet/assets/124715224/9bb07ce0-b4c7-4603-b2d4-8d54775e90ae)

![image](https://github.com/vitessio/arewefastyet/assets/124715224/19b70831-440e-4b6d-9575-9ee010944cad)

**Comment by DhairyaMajmudar** [comment]
@frouioui pls. once approve this issue. I would love to open a PR for this 

Thank you =)

**Comment by frouioui** [comment]
That's not a bad idea, we have the same type of templates in vitess: https://github.com/vitessio/vitess/tree/main/.github/ISSUE_TEMPLATE.

If you have time to work on this go ahead!

**Comment by DhairyaMajmudar** [comment]
Sure looking forward for this
