### ISSUE TITLE
Feat: Converting HTML buttons into ShadCn Button componets  

### ISSUE THREAD

**Issue by DhairyaMajmudar** [vitessio/arewefastyet#534]
**Is your feature request related to a problem? Please describe.**
In the website, some files are using HTML buttons even though new ShadCn buttons are added.

The motive of this issue is to convert those HTML buttons into ShadCn Button components to maintain consistency in the codebase.  

**Describe the solution you'd like**
Files having HTML buttons ( Searched with the help of vs code search feature )

1. `website/src/common/Dropdowns.tsx`
2. `website/src/pages/MacroQueriesComaprePage/components/QueryPlan.tsx`
3. `website/src/utils/Error/Error.tsx`

**Describe alternatives you've considered**
N/A
 
**Additional context**
N/A

**Comment by DhairyaMajmudar** [comment]
Florent pls. share your views on this.

**Comment by frouioui** [comment]
Let's do this! You are welcome to open a PR. Simplifying the code by using only the same source will for sure be useful.
