### ISSUE TITLE
Feat: converting `error.css` file into tailwind classes 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [vitessio/arewefastyet#535]
**Is your feature request related to a problem? Please describe.**
Even website codebase is shifted to using tailwind CSS utility classes the  files `utils/Error.tsx` still uses the vanilla CSS imported from `error.css` file. 

**Describe the solution you'd like**
To transfer Vanilla CSS  to tailwind CSS utility classes in Error.tsx file.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by frouioui** [comment]
Sounds like a good idea to me.

**Comment by DhairyaMajmudar** [comment]
Thanks, Florent I have opened PRs of resolving these pls. have a look : )
