### ISSUE TITLE
Microbenchmarks: Use existing benchmark tests

### ISSUE THREAD

**Issue by systay** [vitessio/arewefastyet#62]
The existing performance benchmarks are end-to-end. This is really great.

Just like in testing, end-to-end is well supported by testing/benchmarking of smaller units.

Today, we have a few `func BenchFoo(b *testing.B)`  method sprinkled throughout the code base.

It would be awesome if we could pick use these benchmarks and just start running them, collecting numbers and then creating a pretty charts for them.

**Comment by frouioui** [comment]
Pull request #70 focuses on collecting the benchmarks, running them, and saving their results. Creating charts for them will be covered by a subsequent pull request.

**Comment by frouioui** [comment]
> It would be awesome if we could pick use these benchmarks and just start running them, collecting numbers

- [ ] Microbenchmarks: use existing tests #70

> and then creating a pretty charts for them.

- [ ] Render microbenchmarks in the UI through a table #79
